import Head from 'next/head'
import { Inter, Roboto, Acme } from 'next/font/google'
import Navbar from '@/components/Navbar'
import Header from '@/components/Header'
import { useRouter } from 'next/router'

const acme = Acme({ subsets: ['latin'], weight: '400' })

export default function Home() {
  const router = useRouter()
  return (
    <>
      <Head>
        <title>Početna</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header type='video' path='/ganjgolineweb1.mp4'>
        <Navbar>
          <div className='z-20 flex flex-col items-center justify-center p-20 '>
            <div className='w-1/2 text-center space-y-9'>
              <h2 className='text-4xl font-bold tracking-wider 2xl:text-5xl'>
                Dobro došli na web stranicu Ganjgo line d.o.o.
              </h2>
              <p className='text-lg font-semibold tracking-wider 2xl:text-2xl'>
                Na našem tehničkom pregledu dočekaće Vas stručno i ljubazno osoblje sa vrhunskom kvalitetom usluge
              </p>
              <button
                onClick={() => router.push('/kontakt')}
                className='px-8 py-2 bg-gradient-to-r from-[#0219AC] to-[#2D63F6] rounded-full uppercase 2xl:text-xl 2xl:font-semibold 2xl:px-10 2xl:py-4'
              >
                Kontakt
              </button>
            </div>
          </div>
        </Navbar>
      </Header>
    </>
  )
}
