import Head from 'next/head'
import { Inter, Roboto, Acme } from 'next/font/google'
import Link from 'next/link'
import Image from 'next/image'
import { BsSearch } from 'react-icons/bs'
import { useRouter } from 'next/router'
import ActiveLink from '@/components/ActiveLink'

const acme = Acme({ subsets: ['latin'], weight: '400' })

export const navigationMenu = [
  {
    id: 1,
    name: 'Početna',
    path: '/',
  },
  {
    id: 2,
    name: 'O nama',
    path: '/o_nama',
  },
  {
    id: 3,
    name: 'Usluge',
    path: '/usluge',
  },
  {
    id: 4,
    name: 'Galerija',
    path: '/galerija',
  },
]

export default function Home() {
  return (
    <>
      <Head>
        <title>Početna</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <header className='relative h-[500px] xl:h-screen overflow-hidden '>
        <div className='absolute top-0 left-0 z-10 w-full h-full opacity-100 bg-slate-50/20'></div>
        <div className='bg-gradient-to-r from-[#0219AC] to-[#2D63F6] h-full w-full absolute left-0 top-0 opacity-100'></div>
        <video
          className='absolute z-0 w-auto h-auto min-w-full min-h-full transform -translate-x-1/2 -translate-y-1/2 top-[45%] left-1/2'
          // className='absolute top-0 left-0 z-0 w-full h-full object-fit contain'
          autoPlay
          loop
          muted
          playsInline
        >
          <source src='/ganjgolineweb1.mp4' type='video/mp4' />
        </video>

        <div className='relative z-10 text-white'>
          {/* NAVBAR */}
          <nav className='container mx-auto'>
            <div className='flex items-center justify-around mr-16'>
              <Link href='/' className=''>
                <Image src='/images/logo.png' alt='logo' width='300' height='300' />
              </Link>

              <div className='space-x-4 '>
                {navigationMenu.map((el) => (
                  <ActiveLink href={el.path} key={el.id} className='text-xl font-semibold'>
                    {el.name}
                  </ActiveLink>
                ))}
              </div>

              <div className='flex items-center justify-center space-x-6'>
                <BsSearch size={25} />
                <button className='px-8 py-2 bg-gradient-to-r from-[#0219AC] to-[#2D63F6] rounded-full'>Kontakt</button>
              </div>
            </div>
          </nav>

          {/* TEXT */}
          <div className='z-20 flex flex-col items-center justify-center p-20 '>
            <div className='w-1/2 text-center space-y-9'>
              <h2 className='text-4xl font-bold tracking-wider 2xl:text-5xl'>
                Dobro došli na web stranicu Ganjgo line d.o.o.
              </h2>
              <p className='text-lg font-semibold tracking-wider 2xl:text-2xl'>
                Na našem tehničkom pregledu dočekaće Vas stručno i ljubazno osoblje sa vrhunskom kvalitetom usluge
              </p>
              <button className='px-8 py-2 bg-gradient-to-r from-[#0219AC] to-[#2D63F6] rounded-full uppercase 2xl:text-xl 2xl:font-semibold 2xl:px-10 2xl:py-4'>
                Kontakt
              </button>
            </div>
          </div>
        </div>
      </header>
    </>
  )
}
