import Header from '@/components/Header'
import Navbar from '@/components/Navbar'
import Head from 'next/head'
import React from 'react'

const About = () => {
  return (
    <>
      <Head>
        <title>O nama</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header type='image' path='/images/o_nama.jpg'>
        <Navbar>
          <div className='z-20 flex flex-col items-center justify-center p-20 '>
            <div className='w-1/2 text-center space-y-9'>
              <h2 className='text-4xl font-bold tracking-wider 2xl:text-5xl'>O nama</h2>
              <p className='text-lg font-semibold tracking-wider 2xl:text-2xl'>
                Dolaskom u Ganjgo centar dočekaće Vas stručno i ljubazno osoblje, brza i kvalitetna usluga i povoljne
                cijene!
              </p>
            </div>
          </div>
        </Navbar>
      </Header>
    </>
  )
}

export default About
