import Header from '@/components/Header'
import Navbar from '@/components/Navbar'
import Head from 'next/head'
import Image from 'next/image'
import React from 'react'

const About = () => {
  return (
    <>
      <Head>
        <title>O nama</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header type='image' path='bg-[url("/images/o_nama.jpg")]' classes=''>
        <Navbar>
          <div className='z-20 flex flex-col items-center justify-center p-10 mt-10 md:p-20 md:mt-28'>
            <div className='text-center md:w-1/2 space-y-9'>
              <h2 className='text-4xl font-bold tracking-wider 2xl:text-5xl'>O nama</h2>
              <p className='text-lg font-semibold tracking-wider 2xl:text-2xl md:block'>
                Dolaskom u Ganjgo centar dočekaće Vas stručno i ljubazno osoblje, brza i kvalitetna usluga i povoljne
                cijene!
              </p>
            </div>
          </div>
        </Navbar>
      </Header>

      {/* KOLEKCIJA SLIKA */}
      <section className='bg-[#171B29] text-white p-5 md:px-10 md:py-14 text-lg leading-8'>
        <p>
          Ganjgo line d.o.o. posluje od 2007. godine sa sjedištem u općini Doboj Jug na adresi 203 brigade br.88
          Matuzići. Osnovna djelatnost naše firme jeste usluge tehničkog pregleda svih vrsta vozila. U sklopu tehničkog
          pregleda nudimo i baždarenje(ispitivanje) i ugradnja svih vrsta analognih i digitalnih tahografa kao i nove
          smart tahografe. U našem objektu također imamo i homologaciju,certifikaciju,sve vrste atesta, ADR vozilima,
          atesti plina, cemt potvrde o usklađenosti vozila. Nudimo usluge servisa,baždarenje,punjenje i prodaju
          vatrogasni aparata. Cilj je da naši kupci budu što zadovoljni te da imaju sve na jednom mjestu, tu su i
          osiguravajuće kuće. Ganjgo line nudi i usluge transporta na lokaciji Njemačke, Francuske, Holandije, Belgije,
          Španije...
        </p>
        <div className='grid grid-cols-3 grid-rows-3 gap-3 mt-8 md:gap-6'>
          <div className='col-span-2 row-span-2'>
            <Image
              width={2000}
              height={1000}
              src='/images/homologacija.jpg'
              alt='homologacija'
              className='object-cover min-h-full'
            />
          </div>
          <div className='col-span-1'>
            <Image width={2000} height={1000} src='/images/3_auta.jpg' alt='3_auta' />
          </div>
          <div className='col-span-1 row-span-2'>
            <Image
              width={2000}
              height={1000}
              src='/images/popravak.jpg'
              alt='popravak'
              className='object-cover min-h-full'
            />
          </div>
          <div className='col-span-1'>
            <Image
              width={1000}
              height={1000}
              src='/images/benzinska.jpg'
              alt='benzinska'
              className='object-cover min-h-full'
            />
          </div>
          <div className='col-span-1'>
            <Image width={1000} height={1000} src='/images/auto.jpg' alt='auto' className='object-cover min-h-full' />
          </div>
          <div className='col-span-1'>
            <Image
              width={1000}
              height={300}
              src='/images/vatrogasno.jpg'
              alt='vatrogasno'
              className='object-cover min-h-full'
            />
          </div>
          <div className='col-span-2 '>
            <Image width={1300} height={1000} src='/images/ulaz.jpg' alt='ulaz' className='object-cover min-h-full' />
          </div>
        </div>
      </section>

      {/* HISTORIJA */}
      <section className='bg-[#24262B] text-white p-5 md:p-10 leading-8 text-xl md:text-2xl'>
        <h2 className='text-center '>Pored firme Ganjgo line u našem centru nalaze se još tri firme.</h2>
        <div className='grid grid-cols-1 gap-6 py-10 text-xl md:grid-cols-2'>
          <div className='md:col-span-2 bg-[#242D5D] rounded-xl p-8'>
            <p>
              2004. godine registruje se firma Autocentar Ganjgo d.o.o. gdje se vežu za „jako“ ime u automobilskoj
              industriji - HYUNDAI. Autocentar Ganjgo ima i novu dodatnu lokaciju Magistralni put bb, općina Lukavac. U
              servisu se radi i održavanje i punjenje klimatiziranih sistema u vozilima, reparacija i servisiranje svih
              vrsta turbina.
            </p>
          </div>
          <div className='col-span-1 bg-[#242D5D] rounded-xl p-8'>
            <p>
              Ganjgo Petrol d.o.o. kao prva firma osnovana 1997. godine, koja se bavi prodajom nafte i naftni derivata.
              Također za naše kupce u sklopu Ganjgo Petrola je i caffe bar.
            </p>
          </div>
          <div className='col-span-1 bg-[#242D5D] rounded-xl p-8'>
            <p>
              U sklopu našeg centra posluje i firma Kam i Bus d.o.o. od 2013. godine koja je u vlasništvu Auto Hrvatska
              d.d. iz Zagreba, koja se bavi prodajom rabljenih privrednih vozila iz teretnog programa i njihovo
              održavanje.
            </p>
          </div>
        </div>
      </section>
    </>
  )
}

export default About
